version: '3'

services:
  nginx:
    image: nginx:latest
    command: nginx -g "daemon off";
    ports:
        - "8080:80"
    volumes:
        - ../src:/var/www/html
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/sites/:/etc/nginx/sites-available
        - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
        - php-fpm

  php-fpm:
    image: php:7-fpm
    expose: 
        - 9000
    volumes:
        - ../src:/var/www/html

  mysql:
    build:
      context: ./mysql
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
